springdoc:
  api-docs:
    # OpenAPI ??? ??(JSON)
    path: /v3/api-docs
  swagger-ui:
    # OpenAPI ??? ??(HTML)
    path: /swagger-ui.html
    # ?? ?? ?? ??
    display-request-duration: true
    # HTTP ??? ???? ??
    operations-sorter: method


# application.yaml
spring:
  profiles:
    active: dev  # 기본 실행 프로파일(dev/deploy 중 선택)

# 공통 설정
server:
  port: 8080


# logging ??
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

file:
  upload:
    all:
      path: ./files
